<?php

namespace Database\Seeders;

use App\Models\Cultura;
use Illuminate\Database\Seeder;

class CulturaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $keys = [
            'id',
            'nome',
            'familia',
            'saturacao_al',
            'indice_x',
            'saturacao_bases',
            'producao_esperada',
            'espacamento',
            'calagem',
            'adubacao_org',
            'observacoes',
            'parcelamento_npk',
            'obs_quadro_npk',
        ];

        $values = [
            [1, 'Couve-Flor', 'Brassicaceae', 5, '3.0', 70, '25.000 kg ou 1.400 dúzias ou 3.000 engradados.', '1,0 x 0,5 m', 'Elevar a saturação por bases do solo a 70% ou pelo método Al<sup>3+</sup> e o do Ca<sup>2+</sup> + Mg<sup>2+</sup> com o valor de X = 3,0 e mt = 5 %.', 'Aplicar 20 t/ha de esterco de curral curtido ou 5 t/ha de esterco de galinha nos sulcos de plantio.', 'Exigente em magnésio.', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK no sulco, por ocasião do transplantio das mudas. Aplicar o restante dos fertilizantes com nitrogênio e potássio em cobertura aos 20, 40 e 60 dias do transplantio. Sugere-se aplicar micronutrientes , especialmente o boro no solo e o molibdênio via foliar.', 'Podem-se colocar 100 kg/ha para repor a quantidade retirada pelas cabeças.'],
            [2, 'Chuchu', 'Cucurbitaceae', 5, '3.5', 80, '60.000 a 65.000 kg/ha', '4,0 x 3,0 m', 'Aplicar calcário para elevar a saturação por bases do solo a 80%.', 'Adicionar 10 t/ha de esterco de curral curtido ou 2,5 t/ha de esterco de galinha, 10 a 20 dias antes do plantio. Após seis meses, repetir a aplicação na mesma quantidade.', 'Exigentes em magnésio.', '<b>N</b> - Aplicar 30 kg/ha no plantio e, a partir do início da produção, aplicar mensalmente 40 kg/ha.<br><b>K</b> - Aplicar 20% da quantidade recomendada no plantio e, a partir do início de produção, fazer adubações mensais com 30 kg/ha.<br><b>P</b> - Aplicar 70% da quantidade recomendada no plantio, e o restante dividir em duas aplicações em cobertura, com chegamento de terra, sendo a primeira 4 meses após o plantio e a segunda 4 meses após a primeira. Utilizar adubos que contêm cálcio solúvel, como nitrocálcio e superfosfato simples, para evitar a deficiência do cálcio (“fruto sem pescoço”).', 'Somente em cobertura.'],
            [3, 'Abóbora Italiana', 'Cucurbitaceae', 5, '3.0', 70, '15.000 a 18.000 kg/ha', '1,0 x 0,7 m', 'Elevar a saturação por bases do solo a 70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>, ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> levando em consideração o valor de Y, variável em função da capacidade tampão da acidez do solo e X = 3 e m<sub>t</sub> = 5%.', 'Aplicar 15 t/ha de esterco de curral curtido, ou 5 t/ha de esterco de aves curtido ou 1,5 t/ha de torta de mamona fermentada.', 'Exigentes em magnésio', 'O fósforo deve ser aplicado todo no plantio, juntamente com o adubo orgânico, 40 % do nitrogênio e 50 % do potássio recomendado, colocados na cova ou sulco de plantio, 15 a 20 dias antes do semeio ou transplantio. O restante do nitrogênio e potássio deve ser aplicado em cobertura, 20 dias após o semeio ou 25 dias após o transplantio das mudas.', null],
            [4, 'Abóbora Menina', 'Cucurbitaceae', 5, '3.0', 70, '20.000 a 24.000 kg/ha', '3,0 x 2,0 m', 'Elevar a saturação por bases a 65-70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Aplicar 15 t/ha de esterco de curral ou 5 t/ha de esterco de galinha curtidos ou 500 kg/ha de torta de mamona fermentada.', 'Exigentes em magnésio', 'o fósforo, 30 % do nitrogênio e 40 % do potássio devem ser aplicados junto com a adubação orgânica, 15 a 20 dias antes do semeio ou transplantio. O restante do nitrogênio e potássio (70 % e 60 % respectivamente) deve ser aplicado em duas coberturas, sendo a primeira 30 dias após a emergência e a segunda 25 dias após a primeira.', 'Somente em cobertura.'],
            [5, 'Alface', 'Asteraceae', 5, '3.0', 70, '21.000 kg/ha ou 9.000 dúzias ou 1.500 engradados/ha.', '25 x 25 cm', 'Elevar a saturação por bases do solo a 70% ou pelo método do Al<sup>3+</sup> do Ca<sup>2+</sup> Mg<sup>2+</sup> com o valor de X = 3,0 e m<sub>t</sub> = 5%.', 'Adicionar 50 t/ha de esterco de curral curtido ou 12 t/ha de esterco de galinha curtido, com incorporação ao solo do canteiro.', '', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK ao solo, por ocasião do transplantio das mudas. Aplicar o restante dos fertilizantes com nitrogênio e potássio em coberturas 15, 30 e 40 dias após o transplantio. Sugere-se aplicar micronutrientes.', 'Podem-se colocar 60 kg para repor a quantidade retirada pela alface colhida.'],
            [6, 'Alho', 'Liliaceae', 5, '3.0', 70, '10.000 a 12.000 kg/ha', '25 a 30 cm entre fileiras e 7,5 a 10 cm entre plantas.', 'Elevar a saturação por bases a 70% com calcário dolomítico.', 'Aplicar 20 a 40 t/ha de esterco de curral curtido ou 5 a\r\n10 t/ha de esterco de galinha curtido, 15 a 30 dias antes do plantio, nos sulcos e\r\nincorporado. As maiores doses são para os solos arenosos.', null, 'Aplicar todo o fósforo e partes dos fertilizantes que contêm NK nos sulcos, 10 dias antes do plantio. Acrescentar à adubação de plantio 3 kg/ha de B e de 3 a 5 kg/ha de Zn. O restante dos fertilizantes com N e K deve ser aplicado em coberturas aos 50 e 100 dias do plantio. Dependendo do estado vegetativo da cultura, usar quantidades menores de N (até 1/3 da recomendação).', null],
            [7, 'Batata', 'Solanaceae', 15, '2.0', 60, '30.000 kg/ha', '80 x 30 cm', 'Elevar a saturação por bases a 60% ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com Y variável em função da capacidade tampão da acidez do solo\r\ne X = 2,0 e m<sub>t</sub> = 15%.', '', 'Exigentes em magnésio.', 'Aplicar parte dos fertilizantes que contêm NPK no sulco, por ocasião do plantio. Imediatamente antes da amontoa, aplicar o restante do fertilizante e proceder à amontoa. Caso haja duas operações de amontoa, dividir a quantidade dos fertilizantes que serão aplicados no parcelamento em ambas as amontoas. Sugere-se aplicar micronutrientes.', 'Podem-se colocar 150 kg para repor a quantidade retirada pela batata colhida.'],
            [8, 'Batata-Doce', 'Convolvulaceae', 15, '2.0', 60, '20.000 kg/ha (909 caixas K)', 'Entre fileiras 0,80 m e entre plantas 0,30 m', 'Elevar a saturação por bases a 60% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Em solos arenosos, aplicar 10 t/ha de esterco de curral curtido ou de composto orgânico, ou 2,5 t/ha de esterco de aves curtido ou 1,0 t/ha de torta de mamona fermentada.', 'Exigentes em magnésio', 'O fósforo deve ser aplicado todo no plantio juntamente com o adubo orgânico, o potássio e 50 % do nitrogênio. Em cobertura, aplica-se o restante do nitrogênio 30 dias após o plantio das ramas.', null],
            [9, 'Berinjela', 'Solanaceae', 5, '3.0', 70, '25.000 a 70.000 kg/ha', '1,20 x 0,70 m', 'Elevar a saturação por bases a 70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup3</sup>.', 'Adicionar 20 a 40 t/ha de esterco de curral curtido ou 5 a 10 t/ha de esterco de galinha, aplicados 10 a 15 dias antes do plantio, nos sulcos ou nas covas, devendo ser incorporados. As maiores doses são para\r\nsolos arenosos.', null, 'Aplicar todo o fósforo e parte dos fertilizantes NK (preferencial-mente nitrato e sulfato de potássio) no sulco ou covas, 10 a 15 dias antes do plantio. O restante dos fertilizantes com nitrogênio e potássio deve ser aplicado em cobertura a cada 15 dias.', null],
            [10, 'Beterraba', 'Amaranthaceae', 5, '3.0', 65, '40.000 kg/ha (1.818 caixas K)', 'Entre fileiras 0,25 m e entre plantas 0,10 a 0,15 m', 'Elevar a saturação por bases a 70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup3</sup>.', 'Aplicar 30 a 50 t/ha de esterco de curral curtido ou de composto orgânico, ou 8 a 10 t/ha de esterco de aves curtido, ou 3 a 5 t/ha de torta de mamona fermentada, sendo a quantidade maior para os solos arenosos.', 'Exigentes em magnésio', 'O fósforo deve ser aplicado todo no plantio juntamente com o adubo orgânico, o potássio e 60 % do nitrogênio. Em cobertura, aplica-se o restante do nitrogênio 30 dias após a germinação.', null],
            [11, 'Brócolos', 'Brassicaceae', 5, '3.0', 70, '20.000 kg ou 2.000 dúzias ou 13.000 maços.', '1,0 x 0,5 m', 'Elevar a saturação por bases do solo a 70% ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com o valor de X = 3,0 e m<sub>t</sub> = 5%.', 'Aplicar 20 t/ha de esterco de curral curtido ou 5 t/ha de esterco de galinha nos sulcos de plantio.', 'Exigentes em magnésio', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK no sulco, por ocasião do transplantio das mudas. Aplicar o restante dos fertilizantes com nitrogênio e potássio em cobertura aos 20, 40 e 60 dias do transplantio. Sugere-se aplicar micronutrientes, especialmente o boro no solo e o molibdênio via foliar.', 'Podem-se colocar 100 kg/ha para repor a quantidade retirada pelas partes colhidas.'],
            [12, 'Cebola', 'Amaryllidaceae', 5, '3.0', 70, '25.000 kg/ha', '20 x 10 cm', 'Elevar a saturação por bases do solo a 70% ou pelo método do do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com o valor de X = 3,0 e m<sub>t</sub> = 5%.', 'Aplicar 40 t/ha de esterco de curral curtido em toda a área de plantio.', null, 'Aplicar todo o fósforo e partes do nitrogênio e do potássio no sulco e o restante destes em cobertura, aos 40 dias do transplantio. Sugere-se aplicar micronutrientes.', 'Podem-se colocar 50 kg/ha para repor a quantidade retirada pelos bulbos.'],
            [13, 'Cenoura', 'Apiaceae', 5, '3.0', 65, '35.000 a 40.000 kg/ha', '15 a 20 cm x 4 a 5 cm', 'Elevar a saturação por bases para 60-70% e o teor de magnésio do solo a um mínimo de 0,8 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Aplicar 30 a 40 t/ha de esterco de curral curtido ou 10 a 13 t/ha de esterco de galinha curtido, sendo a quantidade maior para solos arenosos.', 'Exigentes em magnésio.', '<b>Plantio</b> - Todo o fósforo recomendado, 30% do nitrogênio e 40 % do potássio devem ser aplicados no canteiro junto com o adubo orgânico e incorporados até 15 cm de profundidade, 5 a 10 dias antes do semeio. Se o terreno for deficiente em boro e, ou, em zinco, aplicar 1 a 2 kg/ha de B e, ou, 2 a 3 kg/ha de Zn.<br>\n<b>Adubação de cobertura</b> - O restante do nitrogênio e do potássio (70% e 60% respectivamente) deve ser aplicado em 2 coberturas, aos 20 e aos 40 dias da emergência.', null],
            [14, 'Feijão-Vagem', 'Fabaceae', 5, '3.0', 70, '13.000 a 15.000 kg/ha', '1,0 x 0,5 m', 'Aplicar calcário para elevar a saturação por bases a 70% e atingir, no mínimo, 1 cmol<sub>c</sub>/dm<sup>3</sup> de magnésio ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com o valor de X = 3,0 e m<sub>t</sub> = 5%.', 'Aplicar calcário para elevar a saturação por bases a 70 % e atingir, no mínimo, 1 cmolc/dm3 de magnésio ou pelo método do Al3+ e do Ca2+ + Mg2+ com o valor de X = 3,0 e mt = 5 %.', 'Exigentes em magnésio.', '<b>Plantio</b> - Aplicar 30% do nitrogênio, 50% do potássio e todo fósforo no plantio.<br><b> Cobertura</b> - Parcelar em duas aplicações o restante do nitrogênio (70%) e do potássio (50 %), aos 30 e aos 60 dias da emergência das plântulas. Fazer uma aplicação foliar de molibdato de amônio (0,4 g/L) antes da floração.', null],
            [15, 'Inhame', 'Dioscoreaceae', 10, '2.5', 60, '30.000 kg/ha (1.500 sacos ou 1.363 caixas).', 'Entre fileiras, 0,80 a 0,60 m e entre plantas, 0,50 a 0,40 m.', 'Elevar a saturação por bases a 60% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Em solos arenosos, aplicar 10 t/ha de esterco de\r\ncurral curtido ou de composto orgânico, ou 2,5 t/ha de esterco de aves curtido\r\nou 2,0 t/ha de torta de mamona fermentada.', 'Exigentes em magnésio.', 'O fósforo deve ser aplicado todo no plantio, juntamente com o adubo\r\norgânico, o potássio e 50 % do nitrogênio. Em cobertura, aplica-se o restante do\r\nnitrogênio, 30 dias após a brotação dos rizomas.', null],
            [16, 'Jiló', 'Solanaceae', 5, '3.0', 70, '20.000 a 50.000 kg/ha', '1,20 x 0,70 m', 'Elevar a saturação por bases a 70% com calcário dolomítico ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com Y variável em função da capacidade tampão da acidez do solo e X = 3,0 e m<sub>t</sub> = 5%.', 'Aplicar 20 a 40 t/ha de esterco de curral curtido ou 5 a 10 t/ha de esterco de galinha curtido, 10 a 15 dias antes do plantio, nos sulcos ou nas covas, devendo ser incorporados. As maiores quantidades são para solos arenosos.', null, 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK\r\n(preferencialmente nitrato e sulfato de potássio) no sulco ou covas, 10 a 15 dias\r\nantes do plantio. O restante dos fertilizantes com nitrogênio e potássio deve ser\r\naplicado em cobertura a cada 15 dias.', null],
            [17, 'Mandioquinha-Salsa', 'Apiaceae', 5, '3.0', 65, '12.000 kg/ha (545 caixas K).', 'Entre fileiras, 0,80 a 0,60 m, e entre plantas, 0,50 a 0,40 m.', 'Elevar a saturação por bases a 60% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Em solos arenosos, aplicar 5 t/ha de composto\r\norgânico ou de esterco de curral curtido.', 'Exigentes em magnésio', 'O fósforo deve ser aplicado todo no plantio juntamente com o potássio.', null],
            [18, 'Melancia', 'Cucurbitaceae', 5, '3.0', 70, '30.000 kg/ha', '2,0 a 2,5 x 2,0 m', 'Aplicar calcário para elevar a saturação por bases a 65 - 70% e o teor de magnésio para, no mínimo, 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Adicionar 10 t/ha de esterco de curral ou 3 t/ha de esterco de galinha, aplicados na cova 20 dias antes do semeio ou transplantio.', 'Exigentes em magnésio.', '<b>Plantio</b> - Colocar junto com o adubo orgânico, 30% do nitrogênio, 40% do potássio e todo o fósforo recomendado.<br><b>Cobertura</b> - Aplicar o restante do nitrogênio e do potássio (70% e 60%, respectivamente), parcelado em três vezes, sendo a primeira 15 dias após o transplantio ou 20 dias após a germinação, e as demais espaçadas de 20 dias uma da outra.', 'Somente em cobertura.'],
            [19, 'Melão', 'Cucurbitaceae', 5, '3.5', 80, '25.000 a 35.000 kg/ha.', '2,00 x 0,5 m', 'Elevar a saturação por bases a 80% com calcário dolomítico ou magnesiano, se inferior a 70%.', 'Adicionar 20 a 40 t/ha de esterco de curral curtido ou 5 a 10 t/ha de esterco de galinha, 30 dias antes do plantio. Aplicar na superfície do solo e incorporar até 20 cm de profundidade. As maiores quantidades são para solos arenosos, preferencialmente do esterco de curral.', 'Exigentes em magnésio.', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK nos sulcos ou covas, 15 dias antes do plantio. O restante dos fertilizantes com nitrogênio e potássio deve ser aplicado em cobertura a cada 10 dias. Caso a cultura seja fertirrigada, as quantidades de N e K devem ser distribuídas diariamente.<br><br>É recomendável aplicar a solução 5 g/L de cloreto de cálcio e 1,5 g/L de ácido bórico ou soluções quelatizadas em pulverizações foliares a partir do início do aparecimento dos frutos e a intervalos de 10 dias. Podem ser aplicados juntos com os defensivos.', null],
            [21, 'Moranga Híbrida', 'Curcubitaceae', 5, '3.0', 70, '1.200 kg/ha (480 sacos)', 'Entre fileiras 2,0 m, entre covas 2,0 m', 'Elevar a saturação por bases a 70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Aplicar 5 t/ha de esterco de curral curtido ou de composto orgânico, ou 1,5 t/ha de esterco de aves curtido, ou 0,5 t/ha de torta de mamona fermentada.', 'Exigentes em magnésio.', 'O fósforo deve ser aplicado todo, 20 dias antes do plantio, juntamente com o adubo orgânico, o potássio e 1/3 do nitrogênio. Em cobertura, aplica-se o restante do nitrogênio 20 dias após a germinação.', null],
            [22, 'Morango', 'Rosaceae', 5, '3.0', 70, '50.000 a 80.000 kg/ha', '0,25 x 0,25 m (indústria) e 0,30 x 0,30 m (mesa).', 'Aplicar calcário quando a saturação por bases for inferior a 70%, devendo elevá-la a 80% com calcário dolomítico ou magnesiano, buscando elevar o teor de Mg no solo ao mínimo de 1 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Aplicar 20 a 40 t/ha de esterco de curral curtido ou 5 a 10 t/ha de esterco de galinha, 30 dias antes do plantio. Aplicar na superfície do canteiro e incorporar até 20 cm de profundidade, As maiores quantidades são para solos arenosos, preferencialmente do esterco de curral.', 'Exigentes em magnésio', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK 15 dias antes do plantio, misturando nos 10 cm superiores do solo. O restante dos fertilizantes com nitrogênio e potássio deve ser aplicado a cada mês. Pelo menos a metade do potássio deve ser fornecida como sulfato de potássio.<br><br> É recomendável fazer quatro aplicações foliares de solução de uréia a 5 g/L por semana, a partir do plantio. Caso haja produção de frutos deformados recomendam-se três aplicações de solução de ácido bórico a 1,5 g/L, a cada semana, durante o florescimento.', null],
            [23, 'Pepino', 'Cucurbitaceae', 5, '3.0', 70, '30.000 a 35.000 kg/ha.', '1,0 x 0,4 a 0,6 m', 'Aplicar calcário para elevar a saturação por bases a 75% e o teor de magnésio a 1 cmol<sub>c<sub>/dm<sup>3</sup>.', 'Aplicar 25 t/ha esterco de curral ou 8 t/ha de esterco de\r\naves ou 2,5 t/ha de torta de mamona fermentada, 20 a 30 dias antes do semeio\r\nou transplantio das mudas.', 'Exigentes em magnésio.', '<b>Plantio</b> - Aplicar junto com o adubo orgânico 30 % do nitrogênio, 40 % do potássio e todo o fósforo recomendados. Em solos deficientes, acrescentar 1 kg/ha de B e 3 kg/ha de Zn.<br><b>Cobertura</b> - Aplicar o restante do nitrogênio e potássio (70% e 60% respectivamente), parcelado em três vezes, sendo a primeira 15 dias após o transplantio ou 20 dias após a germinação, e as demais parcelas espaçadas de 20 dias uma da outra.', 'Somente em cobertura.'],
            [24, 'Pimentão', 'Solanaceae', 5, '3.0', 70, '30.000 kg/ha (3.000 caixas K).', 'Entre fileiras 1,2 m a 1,0 m, entre plantas 0,60 a 0,40 m', 'Elevar a saturação por bases a 70% e o teor de magnésio do solo a um mínimo de 1,0 cmol<sub>c</sub>/dm<sup>3</sup>.', 'Aplicar 30 dias antes do plantio, 25 t/ha de esterco de curral curtido ou de composto orgânico, ou 5 t/ha de esterco de aves curtido, ou 2,5 t/ha de torta de mamona fermentada.', null, 'Aplicar parte dos fertilizantes que contêm NPK no sulco, por ocasião do transplantio das mudas. Aplicar o restante dos fertilizantes com nitrogênio e potássio em coberturas, a cada 15 dias após o transplantio. Sugere-se aplicar micronutrientes', 'Podem-se colocar 80 kg/ha para repor a quantidade retirada pelos frutos.'],
            [25, 'Quiabo', 'Malvaceae', 5, '3.0', 70, '15.000 a 20.000 kg/ha', '1,0 x 0,20 a 0,30 m', 'Aplicar calcário para elevar o índice de saturação por bases para 70%.', 'Aplicar 50 t/ha de esterco de curral curtido nos sulcos\r\nde plantio.', 'Exigentes em magnésio.', '<b>Plantio</b> - Aplicar no plantio 20% do nitrogênio, 40% do potássio e todo o fósforo recomendados.<br><b>Cobertura</b> - O restante do nitrogênio (80%) e do potássio (60%) deve ser parcelado em três vezes, aos 20, 40 e 60 dias da emergência das plântulas.', 'Somente em cobertura.'],
            [26, 'Repolho', 'Brassicaceae', 5, '3.0', 70, '50.000 kg/ha ou 2.000 sc/ha.', '0,8 x 0,3 m', 'Aplicar calcário para elevar a saturação por bases do solo a 70 % ou pelo método do Al<sup>3+</sup> e do Ca<sup>2+</sup> + Mg<sup>2+</sup> com o valor de X = 3,0 e m<sub>t</sub> = 5%.', 'Adicionar 30 t/ha de esterco de curral curtido ou 8 t/ha de esterco de galinha nos sulcos de plantio.', 'Exigentes em magnésio.', 'Aplicar todo o fósforo e parte dos fertilizantes que contêm NK no sulco, por ocasião do transplantio das mudas. Aplicar o restante dos fertilizantes com nitrogênio e potássio em coberturas aos 20, 40 e 60 dias do transplantio.<br><br>Sugere-se aplicar micronutrientes, especialmente o boro no solo e o molibdênio via foliar.', 'Podem-se colocar 100 kg/ha para repor a quantidade retirada pelas cabeças.'],
            [27, 'Tomate rasteiro', 'Solanaceae', 5, '3.0', 70, '70 t/ha de frutos com boas características\r\nagroindustriais.', 'Há duas opções para espaçamento: em fileira simples, 1,3 x 0,2 m; em linhas duplas, 1,3 x 0,5 x 0,2 ', 'Aplicar calcário para elevar a saturação por bases do solo a 70 - 80%, pH entre 6,0 e 6,5.', '', 'Utilizar relação Ca/Mg = 1.', 'A primeira aplicação de fertilizantes em cobertura é efetuada após o desbaste das plantas, com leve incorporação promovida por capina mecânica ou amontoa.<br><br>Sugere-se aplicar 2 a 3 kg/ha de B e 4 kg/ha de Zn no sulco, em solos de baixa fertilidade.', null],
            [28, 'Tomate Tutorado', 'Solanaceae', 5, '3.0', 70, '100 t/ha de frutos de boa aceitação comercial.', '100 x 70 cm, transplantando-se 2 plantas, por vez, deixandose cada uma com a haste principal.', 'Elevar a saturação por bases do solo a 70-80%, pH entre 6,0 e 6,5.', 'É recomendável.', 'Utilizar relação Ca/Mg = 1.', 'Aplicar 2 a 3 kg/ha de B e 4 kg/ha de Zn no sulco, em solo de baixa fertilidade.<br><br>Caso ocorra “podridão apical”, devem-se pulverizar os frutos em formação com solução 6 g/L de cloreto de cálcio comercial, semanalmente, enquanto persistir a ocorrência nos frutos novos.<br><br>A deficiência de magnésio (“amarelo baixeiro”) pode ser corrigida com pulverizações nas folhas de solução 1,5 g/L de sulfato de magnésio, duas a três vezes. A adição de uréia (5 g/L) favorece a absorção foliar do magnésio.<br><br>O termofosfato magnesiano aplicado ao sulco de plantio pode substituir parte do adubo fosfatado mais solúvel e fornece quantidades apreciáveis de magnésio, cálcio, silício e micronutrientes.', null],
        ];

        foreach ($values as $value) {
            $data = array_combine($keys, $value);
            Cultura::create($data);
        }
    }
}
